# Generated by Django 4.2.7 on 2023-12-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('executor', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('descriptions', models.TextField(verbose_name='Описание задачи')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
