# Generated by Django 5.1.dev20231201130304 on 2023-12-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options_task_author_alter_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='executor',
        ),
    ]
