# Generated by Django 5.1.dev20231201130304 on 2023-12-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Состояние')),
                ('meta_info', models.CharField(max_length=100, verbose_name='Мета-информация')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния задач',
            },
        ),
    ]
